title: Digitallik
description: Crypto blog, crypto products, and the DGTK ecosystem.

url: "https://digitallikhq.github.io"
baseurl: "/digitallik"

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown

collections:
  products:
    output: true
    permalink: /products/:name/

x_handle: "DigitallikHQ"
x_url: "https://x.com/DigitallikHQ"
